version: '3.8'

services:
  voice-assistant:
    build: .
    ports:
      - "5050:5050"
    environment:
      - PORT=5050
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    restart: unless-stopped
